<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light dark"><title>{{ $rule?'Editar recurrencia':'Nueva recurrencia' }} · Central ARPYNET</title>
<style>:root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color-scheme:light dark}*{box-sizing:border-box}body{margin:0;background:#0b1020;color:#f8fafc}a{color:inherit;text-decoration:none}button,input,select,textarea{font:inherit}.shell{width:min(100%,960px);margin:0 auto;padding:24px 16px 80px}.topbar{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:24px}.brand{font-weight:850}.hero{margin-bottom:18px}h1{margin:0;font-size:clamp(30px,7vw,46px);letter-spacing:-.05em}.subtitle,.help{color:#94a3b8}.subtitle{margin-top:7px;font-size:13px}.panel{padding:16px;border:1px solid #24304b;border-radius:17px;background:#11182b}.grid{display:grid;gap:11px}.field{display:grid;gap:5px}.field label{color:#cbd5e1;font-size:11px;font-weight:820}.field input,.field select,.field textarea{width:100%;min-height:42px;padding:9px 10px;border:1px solid #334155;border-radius:10px;background:#0f172a;color:#f8fafc}.field textarea{min-height:90px;resize:vertical}.check{display:flex;align-items:center;gap:8px;min-height:42px;color:#cbd5e1;font-size:12px;font-weight:800}.check input{width:auto;min-height:auto}.help{font-size:10px}.section-title{margin:18px 0 10px;color:#93c5fd;font-size:12px;font-weight:850;text-transform:uppercase;letter-spacing:.05em}.actions{display:flex;flex-wrap:wrap;gap:9px;margin-top:15px}.primary,.secondary{display:inline-flex;align-items:center;justify-content:center;min-height:42px;padding:9px 13px;border-radius:10px;font-size:12px;font-weight:850}.primary{border:0;background:#2563eb;color:#fff;cursor:pointer}.secondary{border:1px solid #334155;background:#0f172a;color:#cbd5e1}.success,.errors,.readonly{margin-bottom:14px;padding:11px 13px;border-radius:12px;font-size:12px}.success{border:1px solid #166534;background:#052e16;color:#bbf7d0}.errors{border:1px solid #991b1b;background:#450a0a;color:#fecaca}.readonly{border:1px solid #475569;background:#0f172a;color:#cbd5e1}@media(min-width:720px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}.span-2{grid-column:1/-1}}@media(max-width:620px){.topbar{align-items:flex-start;flex-direction:column}}@media(prefers-color-scheme:light){body{background:#f8fafc;color:#0f172a}.panel{background:#fff;border-color:#e2e8f0}.field input,.field select,.field textarea,.secondary{background:#fff;color:#0f172a;border-color:#cbd5e1}.field label,.check{color:#334155}.readonly{background:#fff;color:#475569;border-color:#cbd5e1}}</style></head>
<body>
<div class="shell"><header class="topbar"><a class="brand" href="{{ route('daily-ops.show') }}">Central ARPYNET</a><x-operational-nav active="daily" /></header>
@if(session('recurring_task_success'))<div class="success">{{ session('recurring_task_success') }}</div>@endif
@if($errors->any())<div class="errors">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
<section class="hero"><h1>{{ $rule?'Editar recurrencia':'Nueva recurrencia' }}</h1><div class="subtitle">Define el ciclo; CENTRAL generará las tareas operativas correspondientes.</div></section>
@if(!$canWrite)<div class="readonly">Tienes acceso de solo lectura a esta recurrencia.</div>@endif
@php $organizationId=(int)old('organization_id',$rule?->organization_id ?? $defaultOrganizationId);$selectedProject=(int)old('project_id',$rule?->project_id ?? 0);$selectedAssignee=(int)old('assigned_to',$rule?->assigned_to ?? auth()->id()); @endphp
<section class="panel"><form method="post" action="{{ $rule?route('recurring-task-front.update',$rule):route('recurring-task-front.store') }}">@csrf
<div class="section-title">Tarea</div><div class="grid">
<div class="field"><label for="organization_id">Empresa / ámbito</label><select id="organization_id" name="organization_id" {{ $rule||!$canWrite?'disabled':'' }} required>@foreach($organizations as $organization)<option value="{{ $organization->id }}" @selected($organizationId===(int)$organization->id)>{{ $organization->name }}</option>@endforeach</select>@if($rule)<input type="hidden" name="organization_id" value="{{ $rule->organization_id }}"><div class="help">El ámbito de una recurrencia existente no se cambia desde esta ficha.</div>@endif</div>
<div class="field"><label for="project_id">Proyecto opcional</label><select id="project_id" name="project_id" {{ !$canWrite?'disabled':'' }}><option value="">Sin proyecto</option>@foreach($projectOptions as $id=>$project)<option value="{{ $id }}" data-organization="{{ $project['organization_id'] }}" @selected($selectedProject===(int)$id)>{{ $project['name'] }} — {{ $project['organization_name'] }}</option>@endforeach</select></div>
<div class="field span-2"><label for="title">Título</label><input id="title" name="title" maxlength="255" required value="{{ old('title',$rule?->title) }}" {{ !$canWrite?'disabled':'' }}></div>
<div class="field span-2"><label for="next_action">Próxima acción</label><input id="next_action" name="next_action" maxlength="255" value="{{ old('next_action',$rule?->next_action) }}" {{ !$canWrite?'disabled':'' }}><div class="help">Paso concreto que aparecerá en cada tarea generada.</div></div>
<div class="field span-2"><label for="description">Descripción</label><textarea id="description" name="description" {{ !$canWrite?'disabled':'' }}>{{ old('description',$rule?->description) }}</textarea></div>
<div class="field"><label for="assigned_to">Responsable</label><select id="assigned_to" name="assigned_to" {{ !$canWrite?'disabled':'' }}><option value="">Usuario actual</option>@foreach($assigneeOptions as $id=>$assignee)<option value="{{ $id }}" data-organizations="{{ implode(',',$assignee['organization_ids']) }}" @selected($selectedAssignee===(int)$id)>{{ $assignee['name'] }}</option>@endforeach</select></div>
</div>
<div class="section-title">Recurrencia</div><div class="grid">
<div class="field"><label for="frequency">Frecuencia</label><select id="frequency" name="frequency" {{ !$canWrite?'disabled':'' }} required>@foreach(\App\Models\RecurringTaskRule::frequencyOptions() as $value=>$label)<option value="{{ $value }}" @selected(old('frequency',$rule?->frequency ?? 'weekly')===$value)>{{ $label }}</option>@endforeach</select></div>
<div class="field"><label for="anchor_date">Primera fecha</label><input id="anchor_date" type="date" name="anchor_date" required value="{{ old('anchor_date',$rule?->anchor_date?->format('Y-m-d') ?? now()->toDateString()) }}" {{ !$canWrite?'disabled':'' }}></div>
<div class="field"><label for="end_date">Finaliza opcionalmente</label><input id="end_date" type="date" name="end_date" value="{{ old('end_date',$rule?->end_date?->format('Y-m-d')) }}" {{ !$canWrite?'disabled':'' }}></div>
<div class="field"><label for="create_days_before">Crear con anticipación</label><input id="create_days_before" type="number" min="0" max="90" name="create_days_before" required value="{{ old('create_days_before',$rule?->create_days_before ?? 0) }}" {{ !$canWrite?'disabled':'' }}></div>
<div class="field"><label for="due_time">Hora de vencimiento</label><input id="due_time" name="due_time" maxlength="5" pattern="(?:[01][0-9]|2[0-3]):[0-5][0-9]" required value="{{ old('due_time',$rule?->due_time ?? '17:00') }}" {{ !$canWrite?'disabled':'' }}></div>
<div><label class="check"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$rule?->is_active ?? true)) {{ !$canWrite?'disabled':'' }}> Regla activa</label></div>
</div>
<div class="section-title">Prioridad</div><div class="grid">
<div class="field"><label for="urgency">Urgencia</label><select id="urgency" name="urgency" {{ !$canWrite?'disabled':'' }} required>@foreach(\App\Models\Task::urgencyOptions() as $value=>$label)<option value="{{ $value }}" @selected(old('urgency',$rule?->urgency ?? 'normal')===$value)>{{ $label }}</option>@endforeach</select></div>
<div class="field"><label for="impact">Impacto</label><select id="impact" name="impact" {{ !$canWrite?'disabled':'' }} required>@foreach(\App\Models\Task::impactOptions() as $value=>$label)<option value="{{ $value }}" @selected(old('impact',$rule?->impact ?? 'normal')===$value)>{{ $label }}</option>@endforeach</select></div>
<div class="span-2"><label class="check"><input type="checkbox" name="is_private" value="1" @checked(old('is_private',$rule?->is_private ?? false)) {{ !$canWrite?'disabled':'' }}> Privada</label></div>
</div>
<div class="actions">@if($canWrite)<button class="primary" type="submit" data-busy-label="Guardando…">{{ $rule?'Guardar cambios':'Crear recurrencia' }}</button>@endif<a class="secondary" href="{{ route('recurring-task-front.index') }}">Volver a recurrentes</a><a class="secondary" href="{{ route('daily-ops.show') }}">Volver a Mi día</a></div>
</form></section></div>
<script>(()=>{const org=document.getElementById('organization_id');const project=document.getElementById('project_id');const assignee=document.getElementById('assigned_to');if(!org||org.disabled)return;const filter=()=>{const id=org.value;project?.querySelectorAll('option[data-organization]').forEach(o=>o.disabled=o.dataset.organization!==id);assignee?.querySelectorAll('option[data-organizations]').forEach(o=>o.disabled=!o.dataset.organizations.split(',').includes(id));};org.addEventListener('change',filter);filter();})();</script>
<x-operational-theme /><x-operational-interactions /></body></html>
