<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light dark"><title>Tareas recurrentes · Central ARPYNET</title>
<link
        rel="stylesheet"
        href="{{ asset('central-assets/pages/recurring-tasks-front.css') }}?v=2.39.2"
    ></head>
<body>
@php $createScope=$selectedScope&&in_array($selectedScope,$writableOrganizationIds,true)?$selectedScope:($writableOrganizationIds[0]??null); @endphp
<div class="shell"><header class="topbar"><a class="brand" href="{{ route('daily-ops.show') }}">Central ARPYNET</a><x-operational-nav active="daily" /></header>
<section class="hero"><div><h1>Tareas recurrentes</h1><div class="subtitle">Reglas que generan tareas operativas sin duplicar ciclos.</div></div>@if($createScope)<a class="primary" href="{{ route('recurring-task-front.create',['scope'=>$createScope]) }}">Nueva recurrencia</a>@endif</section>
<form class="filters" method="get" action="{{ route('recurring-task-front.index') }}"><select name="scope"><option value="">Todos los ámbitos</option>@foreach($organizations as $organization)<option value="{{ $organization->id }}" @selected($selectedScope===(int)$organization->id)>{{ $organization->name }}</option>@endforeach</select><input name="q" maxlength="120" value="{{ $search }}" placeholder="Buscar título, descripción o próxima acción"><button type="submit">Buscar</button></form>
<div style="margin-bottom:14px"><a class="secondary" href="{{ route('daily-ops.show') }}">← Volver a Mi día</a></div>
<section class="list">@forelse($rules as $rule)@php $canWrite=in_array((int)$rule->organization_id,$writableOrganizationIds,true); @endphp<article class="card"><div class="card-head"><div><div class="title">{{ $rule->title }}</div><div class="meta">{{ $rule->organization?->name ?? 'Sin ámbito' }}@if($rule->project) · {{ $rule->project->name }}@endif</div></div><span class="pill {{ $rule->is_active?'active':'inactive' }}">{{ $rule->is_active?'Activa':'Inactiva' }}</span></div><div class="pills"><span class="pill">{{ \App\Models\RecurringTaskRule::frequencyOptions()[$rule->frequency] ?? $rule->frequency }}</span><span class="pill">{{ $rule->urgency }}</span><span class="pill">Impacto {{ $rule->impact }}</span>@if($rule->is_private)<span class="pill private">Privada</span>@endif</div><div class="meta">Primera fecha: {{ $rule->anchor_date?->format('d/m/Y') }} · anticipación {{ $rule->create_days_before }} d · vence {{ $rule->due_time }}</div>@if($rule->next_action)<div class="meta">Siguiente: {{ $rule->next_action }}</div>@endif<div class="card-foot"><span class="meta">{{ $rule->assignee?->name ?? 'Sin responsable' }}</span><a class="link" href="{{ route('recurring-task-front.edit',$rule) }}">{{ $canWrite?'Editar':'Ver' }} →</a></div></article>@empty<div class="empty">No hay reglas recurrentes para los filtros seleccionados.</div>@endforelse</section>
</div><x-operational-theme /><x-operational-interactions /></body></html>
